### PR TITLE
Add natural transformations for NonEmptyList

### PR DESCRIPTION
**Pull request by cocoatomo**

### CODE REVIEW

**Comment by Gab-km** [comment]
@cocoatomo Why do the methods Take and TakeFirst for NEL return FuncyList, not NEL?

**Comment by cocoatomo** [comment]
@Gab-km A result of nel.Take(0) has no element, so the type of nel.Take(0) should not be NonEmptyList.

nel.TakeFIrst() always successfully returns some element, since NonEmptyList has at least one element in contrast to FuncyList. Therefore, the return value need not Maybe context and just be T.

**Comment by Gab-km** [comment]
@cocoatomo Should Take(n when n<= 0) return Nil?

**Comment by cocoatomo** [comment]
@Gab-km I just did not know C# has unsigned integer type (such as uint and ulong). I will make modification on argument types of Take.

**Comment by Gab-km** [comment]
@cocoatomo I see.
LINQ's Enumerable.Take takes its count as `int`, and returns an empty sequence when the count is no more than 0. So IMHO, NEL's Take can have its count as `int` too.

**Comment by cocoatomo** [comment]
@Gab-km I have not known about LINQ interface as well. Following LINQ interface, returning Nil is "natural", because Nil represents empty list.
If agreed, I will revert the last commit.

**Comment by Gab-km** [comment]
@cocoatomo OK. Go ahead then I will merge this. :wink:

**Comment by cocoatomo** [comment]
I have reverted it :smile:

**Comment by Gab-km** [comment]
@cocoatomo Thanks a lot! :smile_cat:

**Pull request merged**
